name = input("სახელი: ")
surname = input("გვრი: ")
age = input("ასაკი: ")
country = input("ქვეყანა: ")
colour = input("ფერი: ")
car = input("მანქანა: ")
food = input("საჭმელი: ")
print(name +" " + surname + " " + age + " " + country + " " + colour + " " + car + " " + food)
age = input("მამის ასაკი: ")
age = input("დედის ასაკი: ")
age = input("ძმის ასაკი: ")
age = input("მამის ასაკი 20 წლის შემდეგ: ")
age = input("დედის ასაკი 20 წლის შემდეგ: ")
age = input("ძმის ასაკი 20 წლის შემდეგ: ")
number = input("ჩაწერეთ რიცხვი: ")
number1 = input("ჩაწერეთ რიცხვი: ")
number2 = input("ჩაწერეთ რიცხვი: ")
number3 = input("ჩაწერეთ რიცხვი: ")


print(2+2)
print(2-2)
print(2*2)
print(2//2)
print(2**2)
print(3+3)
print(3-3)
print( 3*3)
print( 3//3)
print( 3**3)
print( 4+4)
print( 4-4)
print( 4*4)
print( 4//4)
print(  4**4)
print( 5+5)
print( 5-5)
print( 5*5)
print(  5//5)
print( 5**5)